# system packages and tasks go here; the other mise.toml is for this repository

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
age = "latest"
btop = { version = "latest", os = ["linux"] }
bun = "latest"
carapace = "latest"
gh = "latest"
gum = "latest"
helix = "latest"
node = "latest"
ripgrep = "latest"
sops = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"

# nushell ships multiple binaries (plugins)
"ubi:nushell/nushell" = { version = "latest", extract_all = true }
