# this mise.toml is for commands related to this repo and installation;
# see `mise.global.toml` for to-be-deployed packages

[tasks.setup]
description = "Install dotfiles"
run = "nu setup/setup.nu"

[tasks.maintenance]
description = "Repo maintenance"
run = [
  "git submodule update --recursive --remote",
  "curl https://mise.run -o setup/mise.run.sh",
]

[tasks.'maintenance.sync-lazygit-config']
description = "Sync lazygit colors from lazyvim's generated copy"
shell = "nu"
run = """
#!/usr/bin/env nu
let conf = open files/_config/lazygit/config.yml
let theme = open ~/.cache/nvim/lazygit-theme.yml
let updated = $conf | update gui.theme $theme.gui.theme
$updated | save -f files/_config/lazygit/config.yml
"""
