# this mise.toml is for commands related to this repo and installation;
# see `mise.global.toml` for to-be-deployed packages

[tasks.setup]
description = "Install dotfiles"
run = "nu setup/setup.nu"

[tasks.update-modules]
description = "Update git submodules"
run = "git submodule update --recursive --remote"
