format = """
[ ](bg:#3d3d3d)[ ](bg:#777777)[ ](bg:#c2c2c2) \
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[character]
format = '$symbol'
success_symbol = '[ ❯ ](bold fg:#3d3d3d bg:#5ac9ef)'
error_symbol = '[ ❯ ](bold fg:#3d3d3d bg:#f87e09)'

[directory]
style = 'bold fg:#5ac9ef'

[git_branch]
style = 'bold fg:#5aa0b9'