theme = "nightfox"

# extend mode keys, using alt for ipad compat
[keys.normal]
"A-u" = "move_visual_line_up"
"A-e" = "move_visual_line_down"
"A-n" = "move_char_left"
"A-i" = "move_char_right"
"A-l" = "goto_line_start"
"A-y" = "goto_line_end"
"A-j" = "page_up"
"A-h" = "page_down"
"A-o" = "delete_char_backward"
"A-;" = "delete_char_forward"
"A-a" = "delete_char_backward"
"A-q" = "normal_mode"

[keys.insert]
"A-u" = "move_visual_line_up"
"A-e" = "move_visual_line_down"
"A-n" = "move_char_left"
"A-i" = "move_char_right"
"A-l" = "goto_line_start"
"A-y" = "goto_line_end"
"A-j" = "page_up"
"A-h" = "page_down"
"A-o" = "delete_char_backward"
"A-;" = "delete_char_forward"
"A-a" = "delete_char_backward"
"A-q" = "normal_mode"
